@startuml Package diagram

component core {
	package movie.core
	package movie.json
}

movie.core ..> movie.json

component gson {
}

movie.json ..> gson

component ui {
    package movie.ui
}

component javafx {
	component fxml {
	}
}

movie.ui ..> javafx
movie.ui ..> fxml

movie.ui ..> movie.json
movie.ui ..> movie.core

component springboot/RESTfull API {
	package movielist.springboot
}

component springboot {
}

springboot/RESTfull API ..> springboot
movielist.springboot ..> movie.core 
movielist.springboot ..> movie.json 

@enduml