@startuml Class Diagram
skinparam Style strictuml
skinparam SequenceMessageAlignment center

class Movie {
 - Title: String 
 - Score: double 
 - Genre: String 
 - Count: int 
 + void setName(String)
 + void setScore(double)
 + void setGenre(String)
 + void addDuplicate()
 + String getName()
 + String getGenre()
 + double getScore()
 + int getCount()
}

class MovieList {
 - Movies: List<Movie>
 + List getMovies()
 + void addMovie(Movie)
 + int getNumberOfMovies()
 + String movieListToString()
 + boolean checkDuplicate()
}

MovieList --o Movie : movies

class AppController {
    - fileHandler: MovieListHandler 
    - movieList: MovieList 
    - MovieList getMovieList()
    - void initialize()
    - void handleAddBtn(ActionEvent)
    - void clearTextFields()
    - void addMovieToList(MovieList)
    - void initializeMovieField()
    - void updateMovieListField()
    - void handleChoise(ActionEvent)
    - void resetGenreBtn()
    - void handleOpenList()
    - void handleSaveList()

}

class MovieListHandler {
    - gson: Gson
    - filePath: String
    + void writeMovieListToFile(MovieList, String) 
    + void writeMovieListToFile(MovieList)
    + MovieList readMovieListFromFile(String)
    + MovieList readMovieListFromFile()
}

MovieListHandler *- MovieList : movielists
AppController *- MovieList : movielists

@enduml