@startuml Package diagram

package "movielist.core.src.main.java.core" {
  class Movie 
  class MovieList 
  class MovieListOverview 
}

package "movielist.core.src.main.java.json" {
  class MovieListHandler 
}

package "movielist.ui.src.main.java.ui" {
  class App 
  class AppController 
}

package "movielist.ui.src.main.resources.ui" {
  class App
}

@enduml


' @startuml Package diagram

' package "movielist" {
'   package "core" {
'     package "src" {
'       package "main" {
'         package "java" {
'           package "core" {
'             class Movie 
'             class MovieList 
'             class MovieListOverview 
'           }
'           package "json" {
'             class MovieListHandler 
'           }
'         }
'       }
'     }
'   }
' }

' package "ui" {
'   package "src" {
'     package "main" {
'       package "java" {
'         package "ui" {
'           class App 
'           class AppController 
'         }
'         package "resources" {
'           package "ui" {
'             class App
'           }
'         }
'         class MovieList             
'       }
'     }
'   }
' }

' @enduml

