@startuml Package diagram

component core {
	package movie.core
	package movie.json
}

movie.core ..> movie.json

component gson {
}

movie.json ..> gson

component ui {
    package movie.ui
}

component javafx {
	component fxml {
	}
}

ui ..> javafx
ui ..> fxml


@enduml